apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ticket-check
  labels:
    app: ticket-check
  name: ticket-check
spec:
  ports:
    - name: proxy
      port: 8888
      protocol: TCP
      targetPort: oauth-proxy
    - name: app
      port: 8080
      protocol: TCP
      targetPort: ticket-check
  selector:
    name: ticket-check
  sessionAffinity: None
  type: ClusterIP
